Get http://localhost:3000/sensors/ 

POST http://localhost:3000/sensors/create HTTP/1.1
content-type: application/json

{ 
   "sensorId": "XYZ1",
    "sensorName": "sensor1",
    "initiator": false,
    "value": "145.25",
    "time": "Wed, 23 May 2018 08:32:39 GMT",
    "ассоuntMijin": "JHGFFT1545GG"
}

Get http://localhost:3000/sensors/all

Get https://arduino-mijin-jvatxphfut.now.sh/device/3

POST http://localhost:3000/device/signal HTTP/1.1
content-type: application/json

{
   "shipmentId": "shrimp-25-05-18",
   "deviceId": "arduino-1",
   "sensorId": "sensor1",   
   "value": 45.65,
   "time": "Wed, 23 May 2018 08:32:39 GMT"
}

POST http://localhost:3000/device/signal HTTP/1.1
content-type: application/json

{
   "shipmentId": "shrimp-25-05-18",
   "deviceId": "arduino-1",
   "sensorId": "sensor2",   
   "value": true,
   "time": "Wed, 31 May 2018 09:32:39 GMT"
}

POST http://localhost:3000/device/signal HTTP/1.1
content-type: application/json

{
   "shipmentId": "shrimp-25-05-18",
   "deviceId": "arduino-1",
   "sensorId": "sensor3",   
   "value": true,
   "time": "Wed, 31 May 2018 09:32:39 GMT"
}

POST https://arduino-mijin-qcpbglakaw.now.sh/device/signal  HTTP/1.1
content-type: application/json

{
   "shipmentId": "shrimp-25-05-18",
   "deviceId": "arduino-1",
   "sensorId": "sensor1",   
   "value": true,
   "time": "Wed, 31 May 2018 09:32:39 GMT"
}

POST http://localhost:3000/buyer/prepay HTTP/1.1
content-type: application/json

{
    "buerCurrency": "XEM",
    "payment": "3",
    "itemName": "XEM",
    "quantityOfGoods": "1",
    "time": "Wed, 31 May 2018 09:32:39 GMT"
} 

Get http://localhost:3000/account

Get http://localhost:3000/address

Get http://localhost:3000/tx
Get https://arduino-iot-nem.herokuapp.com/tx

Get https://arduino-iot-nem.herokuapp.com/device/3
